# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerArticale', models.CharField(max_length=50)),
                ('articale', models.TextField()),
                ('cutArtical', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('autor', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('isReady', models.BooleanField()),
                ('desctiption', models.CharField(max_length=50)),
                ('keyWords', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
