# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160522_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desctiption',
            new_name='description',
        ),
    ]
